name: Update GitHub Repositories

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering

jobs:
  update-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios jq

      - name: Fetch GitHub Repositories
        run: |
          GITHUB_TOKEN='${{ secrets.PAT }}'
          USERNAME='yourusername'
          REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/$USERNAME/repos?per_page=5" | jq -r '.[].html_url')

          # Create a list of repo links in HTML format
          REPO_LIST=""
          for REPO in $REPOS; do
            REPO_LIST="${REPO_LIST}<li><a href=\"$REPO\">$REPO</a></li>"
          done

          # Update index.html with fetched repositories
          sed -i "s|<!--REPLACE_WITH_REPOS-->|$REPO_LIST|g" index.html

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add index.html
          git commit -m "Update GitHub repositories"
          git push https://github.com/${{ secrets.PAT }}@github.com/yourusername/yourrepository.git HEAD:main
