name: Update GitHub Repositories

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch GitHub Repositories
        run: |
          GITHUB_TOKEN='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'
          USERNAME='MaArasteh'
          REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/$USERNAME/repos?per_page=5" | jq -r '.[].html_url')

          # Update index.html with fetched repositories
          sed -i "s|<!--REPLACE_WITH_REPOS-->|$(echo "$REPOS" | sed 's/&/\\\&/g')|g" index.html

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add index.html
          git commit -m "Update GitHub repositories"
          git push
